gpslab/geoip2

- src/Resources/config/services.yml
This is necessary to make it work with Symfony 4. Because in Symfony 4 all services are private by default, so this service cannot be used by default.
> Making geoip2.reader service public

- README.md
- src/Composer/ScriptHandler.php
Hi thanks for this helpful bundle. The update script anticipates the need to use 'bin' rather than 'app' but the method useNewDirectoryStructure is looking for symfony-var-dir option.  I added the symfony-bin-dir directory as an explicit option and the useNewDirectoryStructure method to look for that.  I think this will help keep the script working with projects independent of 'symfony-var-dir' .  Thanks!
> New Symfony 4 bin/composer directory structure

- .travis.yml
* Correct build with PHP 5.4 and 5.5
* HHVM not longer supported
* Test only with [actual](https://symfony.com/roadmap) Symfony versions 2.8, 3.4, 4.2, 4.3
> Correct build and run tests

- UPGRADE-2.0.md
- composer.json
- src/Command/UpdateDatabaseCommand.php
- src/Resources/config/services.yml
The method of decompress the GeoIp database has been changed in #19 and now a `gpslab/compressor` is no longer needed. Remove it.
> Remove gpslab/compressor

- UPGRADE-2.0.md
- composer.json
- src/Command/UpdateDatabaseCommand.php
- src/Resources/config/services.yml
[Stopwatch](https://symfony.com/doc/current/components/stopwatch.html) used to debug performance.
This is not required to update the GeoIP database.
Remove non-cretical dependence.
> Not use Stopwatch

- composer.json
Composer was used for ScriptHandler which was removed in #26, so it not needed anymore. Remove it
> Сomposer is not used anymore

- src/DependencyInjection/Configuration.php
Fix deprecation error
> Using `Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition::cannotBeEmpty()` at path `gpslab_geoip.databases..locales` has no effect, con
sider `requiresAtLeastOneElement()` instead. In 4.0 both methods will behave the same.
> Not use ArrayNodeDefinition::cannotBeEmpty()

- .travis.yml
- phpstan.neon.dist
Run test by PHPStan in Travis CI jobs.
Ignore error of `Phar::decompress()` in PHPStan #37
Exclude `Configuration` class from analyse because it is highly dependent on the version of Symfony.
Line   | src/DependencyInjection/Configuration.php
------ | -------------------------------------------------
42     | Class `Symfony\Component\Config\Definition\Builder\TreeBuilder` does not have a constructor and must be instantiated without any parameters.
188    | Class `Symfony\Component\Config\Definition\Builder\TreeBuilder` does not have a constructor and must be instantiated without any parameters.
Line  | src/DependencyInjection/Configuration.php
------ | ----------------------------
165   | Call to an undefined method `Symfony\Component\Config\Definition\Builder\NodeDefinition::fixXmlConfig( …
> Run test by PHPStan in Travis CI jobs

- phpstan.neon.dist
Error in PHPStan because `Phar::decompress()` return `Phar` was fixed.
Fix #37
> Error in PHPStan was fixed

- README.md
PHP version badge from Travis config is broken.
Use **PHP from Packagist** instead.
https://shields.io/category/platform-support
> Fix PHP version badge in README.md

- README.md
Badge "PHP from Travis config" works again
https://shields.io/category/platform-support
> Badge "PHP from Travis config" works again

- src/DependencyInjection/GpsLabGeoIP2Extension.php
- tests/DependencyInjection/GpsLabGeoIP2ExtensionTest.php
Do not create aliases for the default database if there are no configured databases.
> Do not create aliases for the default database

- README.md
- src/DependencyInjection/Configuration.php
- tests/DependencyInjection/ConfigurationTest.php
List of available values for `edition` configuration option:
* `GeoLite2-ASN`
* `GeoLite2-City`
* `GeoLite2-Country`
It makes no sense to give the opportunity to indicate any values as edition.
> Fix the list of available values for the edition configuration option

- README.md
Due to the limitation of the list of acceptable values ​​for the database edition #56, it makes no sense to show a screenshot of the download page.
> Remove download page image from README file

- .gitignore
- tests/DependencyInjection/GpsLabGeoIP2ExtensionTest.php
- tests/Downloader/MaxMindDownloaderTest.php
```
1) GpsLab\Bundle\GeoIP2Bundle\Tests\DependencyInjection\GpsLabGeoIP2ExtensionTest::testLoad with data set #0 (null)
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'/tmp/GeoLite2-ASN.mmdb'
+'C:\Users\PGRIBA~1\AppData\Local\Temp/GeoLite2-ASN.mmdb'
2) GpsLab\Bundle\GeoIP2Bundle\Tests\DependencyInjection\GpsLabGeoIP2ExtensionTest::testLoad with data set #2 (false)
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'/tmp/GeoLite2-ASN.mmdb'
+'C:\Users\PGRIBA~1\AppData\Local\Temp/GeoLite2-ASN.mmdb'
3) GpsLab\Bundle\GeoIP2Bundle\Tests\Downloader\MaxMindDownloaderTest::testNotFoundDatabase
Failed asserting that 'C:\Users\PGRIBA~1\AppData\Local\Temp/5e7b08f99e6b23.65897103_GeoLite2.tar.gz' matches PCRE pattern …
```
> Fix tests for Windows

- .styleci.yml
Fix errors in Style CI
> Config Issue
> The 'phpdoc_no_empty_return' fixer cannot be disabled because it is not enabled by your preset.
> The 'short_array_syntax' fixer cannot be enabled again because it has already been enabled.
> Correct rules in Style CI config

- .styleci.yml
Disable [`no_superfluous_phpdoc_tags_symfony`](https://docs.styleci.io/fixers#no_superfluous_phpdoc_tags_symfony) Style CI rule.
> Disable no_superfluous_phpdoc_tags_symfony Style CI rule

- .github/workflows/qa.yaml
- .github/workflows/test.yaml
Travis CI takes a very long time to build. Building and testing just one commit can take up to 16 hours. It looks like this problem is related to the migration of https://travis-ci.org to https://travis-ci.com. The https://travis-ci.org domain will be closed later than December 31st, 2020.
> Build from GitHub CI

- README.md
- tests/DependencyInjection/ConfigurationTest.php
The documentation is not very clear #77
> Update configuration docs

- README.md
- composer.json
- src/Downloader/MaxMindDownloader.php
Using \PharData to extract the database file causes an out of memory exception since July 22 for the GeoLite2-City database when using the default 128MB memory_limit on Fedora and other distributions.  Use splitbrain/php-archive to reduce memory usage from 147MB to 18MB.  
Solves https://github.com/gpslab/geoip2/issues/82
> Reduce memory usage of geoip2:update

- .github/workflows/qa.yaml
- .github/workflows/test.yaml
- .phpstan/symfony_4.neon
- composer.json
- src/Command/UpdateDatabaseCommand.php
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/GpsLabGeoIP2Extension.php
- src/Reader/ReaderFactory.php
- tests/DependencyInjection/ConfigurationTest.php
- tests/Reader/ReaderFactoryTest.php
This is a simple PR allowing Symfony 7 components to be used with this bundle.
> Allow Symfony 7

- .github/workflows/test.yaml
- composer.json
- src/Reader/ReaderFactory.php
- tests/Command/DownloadDatabaseCommandTest.php
- tests/Command/UpdateDatabaseCommandTest.php
- tests/Downloader/MaxMindDownloaderTest.php
- Add support `geoip2/geoip2` 3.0
- Fix Code Style
- Fix: ```The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.```
- Test on PHP 8.3
> Add support GeoIP2-php 3.0.0

- src/Command/UpdateDatabaseCommand.php
- tests/Command/UpdateDatabaseCommandTest.php
I needed the bundle not fail in the command because a license has not been set
for my project there are use cases where a license will not be used (its up to the user)
this pr will instead of blindly try a download show a warning when the license is not set and skip the download step.
> Do not download when licence is not set
